In [6]:
import numpy as np
import pandas as pd
df=pd.DataFrame({'Frequency':np.arange(10)})
df

   Frequency
0          0
1          1
2          2
3          3
4          4
5          5
6          6
7          7
8          8
9          9

In [7]:
df['Cumulative frequency']=df['Frequency'].cumsum()
df

   Frequency  Cumulative frequency
0          0                     0
1          1                     1
2          2                     3
3          3                     6
4          4                    10
5          5                    15
6          6                    21
7          7                    28
8          8                    36
9          9                    45

In [10]:
df['relative Frequency'] = df['Frequency']/df['Frequency'].sum()

df

   Frequency  Cumulative frequency  relative Frequency
0          0                     0            0.000000
1          1                     1            0.022222
2          2                     3            0.044444
3          3                     6            0.066667
4          4                    10            0.088889
5          5                    15            0.111111
6          6                    21            0.133333
7          7                    28            0.155556
8          8                    36            0.177778
9          9                    45            0.200000